### ISSUE TITLE
[cloudi_service_oauth1:1.5.1] error while rebar3 "generating package index"

### ISSUE THREAD

**Issue by ReuvenSwirsky** [CloudI/cloudi_service_db_riak#1]

**Comment by okeuday** [comment]
Not sure if you figured this out, but if you change the CloudI dependencies to use the same version the dependencies should be satisfied without errors.  Everything is released together to avoid any problems.

**Comment by ReuvenSwirsky** [comment]
Yeah, I did! That's why I closed it.

Thanks for your response.
