### ISSUE TITLE
Version 1.5.1 in hex.

### ISSUE THREAD

**Issue by michalwski** [CloudI/cloudi_service_db_riak#2]
Is it possible to publish the newest release 1.5.1 to hex? The only version in hex is 1.3.3. And I keep getting this warning from rebar3:
```
===> [cloudi_service_oauth1:1.5.1] Only existing version of cloudi_service_db_riak is 1.3.3 which does not match constraint ~> 1.5.1. Using anyway, but it is not guaranteed to work.
```

**Comment by okeuday** [comment]
The rebar3 warning is a bug in rebar3.  If you want to avoid the warning you can use mix with the hex plugin.  The `cloudi_service_db_riak` repo is currently unmaintained.
